### ISSUE TITLE
cara pull update dari repo master di divisi-mobil-poros ke dalam repo di githubku 

### ISSUE THREAD

**Issue by Zanma** [divisi-mobile-POROS/informasi-dosen#7]
kan ak udah nge fork repo master ke githubku, trus udh diclone ke local disk laptop.. nah biar ak bisa nge update ngambil data-data terbaru di repo master di divisi-mobile-poros gmna ya caranya? kan klo aku pull lewat git base ntar yg dipull repo yg digithubku bukan repo yg di divisi-mobile-poros

**Comment by asamsulfat** [comment]
baca2 lagi @Zanma materi git remote Zan, di KULINER awal pertama kalau ndak salah ada.

Jadi remote itu salah satu fitur di GIT, untuk menghubungkan repository local dengan repository yang ada di server.
Misal kamu buat repoisotry local dengan git init, terus kamu jalanain command 'git remote -v / git remote show' disitu nanti ada list remoteny apa aja.

Kalau kamu mau simpan repo local mu ke server (misal github). Kamu tinggal buat repo di github dan tambahkan remotenya dengan command 'git add remote namaRemote urlnya'

Untuk kasusmu, ketika kamu fork repo master ke repo di akunmu. terus kamu clone repo di akunmu ke repo local. Otomatis sebuah remote namanya origin dibuat di repo localmu. 'origin ini nge refer ke repo di akunmu karena kamu clone dari sana'

Untuk update repo local dari repo master, kamu perlu nambahin remote lagi.
misal git remote add namaRemote urlRepoMaster

ketika kamu mau pull dari master, git pull namaRemote master

convention untuk nama remote dari master biasanya pakai nama 'upstream'

**Comment by Moanrisy** [comment]
di KULINER awal pertama kalau ndak salah ada.

Jadi remote itu salah satu fitur di GIT, untuk menghubungkan repository local dengan repository yang ada di server.
Misal kamu buat repoisotry local dengan git init, terus kamu jalanain command 'git remote -v / git remote show' disitu nanti ada list remoteny apa aja.

Kalau kamu mau simpan repo local mu ke server (misal github). Kamu tinggal buat repo di github dan tambahkan remotenya dengan command 'git add remote namaRemote urlnya'

Untuk kasusmu, ketika kamu fork repo master ke repo di akunmu. terus kamu clone repo di akunmu ke repo local. Otomatis sebuah remote namanya origin dibuat di repo localmu. 'origin ini nge refer ke repo di akunmu karena kamu clone dari sana'

Untuk update repo local dari repo master, kamu perlu nambahin remote lagi.
misal git remote add namaRemote urlRepoMaster

ketika kamu mau pull dari master, git pull namaRemote master

convention untuk nama remote dari master biasanya pakai nama 'upstream'

**Comment by asamsulfat** [comment]
baca2 lagi @Zanma materi git remote Zan, di KULINER awal pertama kalau ndak salah ada.

Jadi remote itu salah satu fitur di GIT, untuk menghubungkan repository local dengan repository yang ada di server.
Misal kamu buat repoisotry local dengan git init, terus kamu jalanain command 'git remote -v / git remote show' disitu nanti ada list remoteny apa aja.

Kalau kamu mau simpan repo local mu ke server (misal github). Kamu tinggal buat repo di github dan tambahkan remotenya dengan command 'git add remote namaRemote urlnya'

Untuk kasusmu, ketika kamu fork repo master ke repo di akunmu. terus kamu clone repo di akunmu ke repo local. Otomatis sebuah remote namanya origin dibuat di repo localmu. 'origin ini nge refer ke repo di akunmu karena kamu clone dari sana'

Untuk update repo local dari repo master, kamu perlu nambahin remote lagi.
misal git remote add namaRemote urlRepoMaster

ketika kamu mau pull dari master, git pull namaRemote master

convention untuk nama remote dari master biasanya pakai nama 'upstream'
